// 待补充
export enum API_CODE {
  SUCCESS = 0,
  // 以下都是错误码
  //10xx 用户与通用层
  UNEXPECTED_ERROR = 1000,
  INVALID_EMAIL = 1001,
  INVALID_CODE = 1002,
  CODE_EXPIRED = 1003,
  CODE_ALREADY_SENT = 1004,
  TOKEN_EXPIRED = 1005,
  TOKEN_INVALID = 1006,
  ADDRESS_ALREADY_BOUND = 1007,
  ADDRESS_NOT_BOUND = 1008,
  USER_DOES_NOT_EXIST = 1011,
  ACCOUNT_DOES_NOT_EXIST = 1012,
  INVALID_PARAMETER = 1014,

  // 30xx 交易与链交互层
  EMPTY_REQUEST = 3001,
  CHAIN_IS_REQUIRED = 3002,
  SIGNED_TX_HEX_IS_REQUIRED = 3003,
  FROM_ADDRESS_IS_REQUIRED = 3004,
  UNSUPPORTED_CHAIN = 3005,
  CONTRACT_ADDRESS_IS_REQUIRED = 3006,
  INVALID_ADDRESS = 3007,
  UNSUPPORTED_ASSET = 3008,
  INVALID_SIGNED_TX_HEX = 3012,
  BROADCAST_TRANSACTION_FAILED = 3015,
  CHAIN_RPC_CALL_FAILED = 3016,
  DATA_SERIALIZATION_FAILED = 3017,

  // 40xx 第三方业务层
  SPONSOR_COVERAGE_FAILED = 4002,
  USDT_QUOTER_IS_NOT_CONFIGURED = 4004,
  VENDOR_NOT_CONFIGURED = 4005,
  ASSET_PRICE_UNAVAILABLE = 4006,

  // 50xx 系统层
  SERVICE_COMPONENT_NOT_INITIALIZED = 5001,
  UPSTREAM_RESPONSE_INVALID = 5002,
}

export const ERROR_CODE_MSG = {
  [API_CODE.UNEXPECTED_ERROR]: "未知错误 / 服务器异常",
  [API_CODE.INVALID_EMAIL]: "邮箱格式错误",
  [API_CODE.INVALID_CODE]: "验证码错误",
  [API_CODE.CODE_EXPIRED]: "验证码已过期",
  [API_CODE.CODE_ALREADY_SENT]: "验证码已发送 (请勿频繁请求)",
  [API_CODE.TOKEN_EXPIRED]: "Token 已过期",
  [API_CODE.TOKEN_INVALID]: "Token 无效",
  [API_CODE.ADDRESS_ALREADY_BOUND]: "地址已绑定",
  [API_CODE.ADDRESS_NOT_BOUND]: "地址未绑定",
  [API_CODE.USER_DOES_NOT_EXIST]: "用户不存在",
  [API_CODE.ACCOUNT_DOES_NOT_EXIST]: "账户不存在",
  [API_CODE.INVALID_PARAMETER]: "参数无效",
  // 30xx 交易与链交互层
  [API_CODE.EMPTY_REQUEST]: "请求为空",
  [API_CODE.CHAIN_IS_REQUIRED]: "缺少链参数",
  [API_CODE.SIGNED_TX_HEX_IS_REQUIRED]: "缺少签名交易 Hex",
  [API_CODE.FROM_ADDRESS_IS_REQUIRED]: "缺少发送方地址",
  [API_CODE.UNSUPPORTED_CHAIN]: "不支持的链",
  [API_CODE.CONTRACT_ADDRESS_IS_REQUIRED]: "缺少合约地址",
  [API_CODE.INVALID_ADDRESS]: "地址无效",
  [API_CODE.UNSUPPORTED_ASSET]: "不支持的资产",
  [API_CODE.INVALID_SIGNED_TX_HEX]: "无效的签名交易 Hex",
  [API_CODE.BROADCAST_TRANSACTION_FAILED]: "广播交易失败",
  [API_CODE.CHAIN_RPC_CALL_FAILED]: "链 RPC 调用失败",
  [API_CODE.DATA_SERIALIZATION_FAILED]: "数据序列化失败",
  // 40xx 第三方业务层
  [API_CODE.SPONSOR_COVERAGE_FAILED]: "资源赞助覆盖失败",
  [API_CODE.USDT_QUOTER_IS_NOT_CONFIGURED]: "USDT 报价器未配置",
  [API_CODE.VENDOR_NOT_CONFIGURED]: "供应商未配置",
  [API_CODE.ASSET_PRICE_UNAVAILABLE]: "资产价格不可用",
  // 50xx 系统层  建议前端对50XX系统级错误进行包装屏蔽，给出"网络繁忙"，或者"系统繁忙，请稍后再试"提示
  [API_CODE.SERVICE_COMPONENT_NOT_INITIALIZED]: "系统繁忙，请稍后再试",  // "服务组件未初始化"
  [API_CODE.UPSTREAM_RESPONSE_INVALID]: "系统繁忙，请稍后再试",  // "上游响应无效"
};
